# Generated by Django 2.2.8 on 2021-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lostAndFound',
            fields=[
                ('id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lost_found',
            },
        ),
    ]
