# Generated by Django 2.2.8 on 2021-03-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='lost_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='lost_place',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='lost_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='lost_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='loster_wechat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='publish_date',
            field=models.CharField(default='2021-01-01', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='remark_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
