# Generated by Django 2.2.8 on 2021-03-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0002_auto_20210317_0544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lostAndFound',
        ),
    ]
