# Generated by Django 2.2.8 on 2021-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210218_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
