# Generated by Django 2.2.8 on 2021-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210218_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='map',
            field=models.CharField(default={'111'}, max_length=255),
            preserve_default=False,
        ),
    ]
