# Generated by Django 2.2.8 on 2021-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='map',
            field=models.CharField(default={'1'}, max_length=255),
        ),
    ]
