# Generated by Django 2.2.8 on 2021-03-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('avatar_url', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('openid', models.CharField(default='', max_length=200)),
                ('province', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
