# Generated by Django 2.2.8 on 2021-03-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lostAndFound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('lost_type', models.CharField(default='', max_length=200)),
                ('wechat', models.CharField(default='', max_length=200)),
                ('remark_info', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('publish_date', models.CharField(default='2021-01-01', max_length=200, null=True)),
                ('user_id', models.CharField(default='', max_length=200, null=True)),
                ('tell', models.CharField(default='', max_length=200, null=True)),
                ('check_times', models.IntegerField(default=0)),
                ('published', models.IntegerField(default=0)),
                ('type', models.CharField(default='0', max_length=200, null=True)),
            ],
            options={
                'db_table': 'lost_and_found',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('avatar_url', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('province', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
