# Generated by Django 2.2.8 on 2021-03-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lostAndFound',
            fields=[
                ('id', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('lost_time', models.CharField(default='', max_length=200)),
                ('lost_place', models.CharField(default='', max_length=200)),
                ('lost_name', models.CharField(default='', max_length=200)),
                ('lost_type', models.CharField(default='', max_length=200)),
                ('loster_wechat', models.CharField(default='', max_length=200)),
                ('remark_info', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('publish_date', models.CharField(default='2021-01-01', max_length=200, null=True)),
                ('userId', models.CharField(default='2021-01-01', max_length=200, null=True)),
            ],
            options={
                'db_table': 'lost_and_found',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
