# Generated by Django 2.2.8 on 2021-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210317_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostandfound',
            old_name='lost_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='lost_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='lost_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='userId',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='lostandfound',
            old_name='lost_type',
            new_name='wechat',
        ),
        migrations.RemoveField(
            model_name='lostandfound',
            name='loster_wechat',
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='user_id',
            field=models.CharField(default='2021-01-01', max_length=200, null=True),
        ),
    ]
