# Generated by Django 2.2.8 on 2021-03-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userfavorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='type',
            new_name='content_type',
        ),
    ]
