# Generated by Django 2.2.8 on 2021-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210318_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
